DataFrame Tasks:
1. Create a DataFrame:
1. Load the above dataset into a Pandas DataFrame.

In [38]:
import pandas as pd

In [39]:
data = {
"Order ID":[1001,1002,1003,1004,1005,1006,1007,1008],
"Customer": ["Alice","Bob","Charlie","Alice","David","Charlie","Bob","Alice"],
"Product": ["Laptop","Phone","Chair","Table","Laptop","phone","Chair","Phone"],
"Category": ["Electronics","Electronics","Furniture","Furniture","Electronics","Electronics","Furniture","Electronics"],
"Quantity": [2,1,4,1,1,2,2,1],
"Price": [800,500,100,250,800,500,100,500],
"Total Sales": [1600,500,400,250,800,1000,200,500]
}
df=pd.DataFrame(data)
df

   Order ID Customer Product     Category  Quantity  Price  Total Sales
0      1001    Alice  Laptop  Electronics         2    800         1600
1      1002      Bob   Phone  Electronics         1    500          500
2      1003  Charlie   Chair    Furniture         4    100          400
3      1004    Alice   Table    Furniture         1    250          250
4      1005    David  Laptop  Electronics         1    800          800
5      1006  Charlie   phone  Electronics         2    500         1000
6      1007      Bob   Chair    Furniture         2    100          200
7      1008    Alice   Phone  Electronics         1    500          500

2. Add a New Column:
 Add a column Discount that gives a 10% discount on total
sales.

In [40]:
df["Discount"]=df["Total Sales"]*0.10

In [41]:
df

,Order ID,Customer,Product,Category,Quantity,Price,Total Sales,Discount
0,1001,Alice,Laptop,Electronics,2,800,1600,160.0
1,1002,Bob,Phone,Electronics,1,500,500,50.0
2,1003,Charlie,Chair,Furniture,4,100,400,40.0
3,1004,Alice,Table,Furniture,1,250,250,25.0
4,1005,David,Laptop,Electronics,1,800,800,80.0
5,1006,Charlie,phone,Electronics,2,500,1000,100.0
6,1007,Bob,Chair,Furniture,2,100,200,20.0
7,1008,Alice,Phone,Electronics,1,500,500,50.0

3. Add a New Row:
o Add a new sales record: Order ID = 1009, Customer =
"Eve", Product = "Tablet", Category = "Electronics",
Quantity = 1, Price = 300, Total Sales = 300.

In [42]:
new_row={
    "Order ID":[1009],
"Customer": ["Eve"],
"Product": ["Tablet"],
"Category": ["Electronics"],
"Quantity": [1],
"Price": [300],
"Total Sales": [300],
"Discount": 300 * 0.10
}
df = pd.concat([df,pd.DataFrame([new_row])],ignore_index=True)
df

,Order ID,Customer,Product,Category,Quantity,Price,Total Sales,Discount
0,1001,Alice,Laptop,Electronics,2,800,1600,160.0
1,1002,Bob,Phone,Electronics,1,500,500,50.0
2,1003,Charlie,Chair,Furniture,4,100,400,40.0
3,1004,Alice,Table,Furniture,1,250,250,25.0
4,1005,David,Laptop,Electronics,1,800,800,80.0
5,1006,Charlie,phone,Electronics,2,500,1000,100.0
6,1007,Bob,Chair,Furniture,2,100,200,20.0
7,1008,Alice,Phone,Electronics,1,500,500,50.0
8,[1009],[Eve],[Tablet],[Electronics],[1],[300],[300],30.0

4. Filter Data:
 Retrieve only the sales records where the Category is
"Electronics".

In [43]:
fil_df = df[df["Category"]=="Electronics"]
fil_df

  Order ID Customer Product     Category Quantity Price Total Sales  Discount
0     1001    Alice  Laptop  Electronics        2   800        1600     160.0
1     1002      Bob   Phone  Electronics        1   500         500      50.0
4     1005    David  Laptop  Electronics        1   800         800      80.0
5     1006  Charlie   phone  Electronics        2   500        1000     100.0
7     1008    Alice   Phone  Electronics        1   500         500      50.0

5. Selection:
 Select the Customer and Total Sales columns.

In [50]:
df["Total Sales"]=pd.to_numeric(df["Total Sales"],errors='coerce')

In [51]:
selected_col = df[["Customer","Total Sales"]]
selected_col

  Customer  Total Sales
0    Alice       1600.0
1      Bob        500.0
2  Charlie        400.0
3    Alice        250.0
4    David        800.0
5  Charlie       1000.0
6      Bob        200.0
7    Alice        500.0
8    [Eve]          NaN

6. Grouping:
 Group the data by Customer and calculate the total sales per
customer.

In [53]:
df['Customer']=df['Customer'].astype(str)

In [54]:
sales = df.groupby("Customer")["Total Sales"].sum().reset_index
sales

<bound method Series.reset_index of Customer
Alice      2350.0
Bob         700.0
Charlie    1400.0
David       800.0
['Eve']       0.0
Name: Total Sales, dtype: float64>

7. Sorting:
 Sort the DataFrame based on Total Sales in descending
order.

In [55]:
sorted_df = df.sort_values(by="Total Sales",ascending=False)
sorted_df

,Order ID,Customer,Product,Category,Quantity,Price,Total Sales,Discount
0,1001,Alice,Laptop,Electronics,2,800,1600.0,160.0
5,1006,Charlie,phone,Electronics,2,500,1000.0,100.0
4,1005,David,Laptop,Electronics,1,800,800.0,80.0
1,1002,Bob,Phone,Electronics,1,500,500.0,50.0
7,1008,Alice,Phone,Electronics,1,500,500.0,50.0
2,1003,Charlie,Chair,Furniture,4,100,400.0,40.0
3,1004,Alice,Table,Furniture,1,250,250.0,25.0
6,1007,Bob,Chair,Furniture,2,100,200.0,20.0
8,[1009],['Eve'],[Tablet],[Electronics],[1],[300],NaN,30.0

8. Apply Function:
 Apply a lambda function to create a new column Sales
Category, where values are labeled as "High" if Total Sales >
1000, otherwise "Low".

In [57]:
df["Sales Category"]=df["Total Sales"].apply(lambda x: "High" if x>1000 else "Low")
df

,Order ID,Customer,Product,Category,Quantity,Price,Total Sales,Discount,Sales Category
0,1001,Alice,Laptop,Electronics,2,800,1600.0,160.0,High
1,1002,Bob,Phone,Electronics,1,500,500.0,50.0,Low
2,1003,Charlie,Chair,Furniture,4,100,400.0,40.0,Low
3,1004,Alice,Table,Furniture,1,250,250.0,25.0,Low
4,1005,David,Laptop,Electronics,1,800,800.0,80.0,Low
5,1006,Charlie,phone,Electronics,2,500,1000.0,100.0,Low
6,1007,Bob,Chair,Furniture,2,100,200.0,20.0,Low
7,1008,Alice,Phone,Electronics,1,500,500.0,50.0,Low
8,[1009],['Eve'],[Tablet],[Electronics],[1],[300],NaN,30.0,Low

9. Save DataFrame:
 Save the final DataFrame as a CSV file named sales_data.csv.

In [59]:
df.to_csv("sales_data.csv",index=False)
df

,Order ID,Customer,Product,Category,Quantity,Price,Total Sales,Discount,Sales Category
0,1001,Alice,Laptop,Electronics,2,800,1600.0,160.0,High
1,1002,Bob,Phone,Electronics,1,500,500.0,50.0,Low
2,1003,Charlie,Chair,Furniture,4,100,400.0,40.0,Low
3,1004,Alice,Table,Furniture,1,250,250.0,25.0,Low
4,1005,David,Laptop,Electronics,1,800,800.0,80.0,Low
5,1006,Charlie,phone,Electronics,2,500,1000.0,100.0,Low
6,1007,Bob,Chair,Furniture,2,100,200.0,20.0,Low
7,1008,Alice,Phone,Electronics,1,500,500.0,50.0,Low
8,[1009],['Eve'],[Tablet],[Electronics],[1],[300],NaN,30.0,Low